### ISSUE TITLE
MyQ Lite (v3.1.3) Momentary Button Error / Automation

### ISSUE THREAD

**Issue by toxsid** [brbeaird/SmartThings_MyQ#105]
Hello @brbeaird 

I have updated to 3.1.3 and notice that the momentary buttons give the following error:

"Can't connect to device. Check device and try again" (opener or closer buttons display this error).

When I try to remove and re-add them I receive the same error, I am only able to open the doors via the device .

Also, in the past I had it setup if the device reads "opening" the light the inside lights turn on using the "Smart Lighting" SmartApp. It appears for some reason this no longer works in the new smartthings app, any other alternatives to do this?

**Comment by brbeaird** [comment]
I just pushed an update 3.1.4. It now uses virtual switch instead of momentary. I suggest you add that device type to your environment and try the setup again.

As for the the inside lights and the "opening" status, I'm not really sure. I'd say you're better off triggering it based on when the door or the virtual switch turns "on."
