### ISSUE TITLE
Door Sensor ICON added to Main ST dashboard instead of a garage door

### ISSUE THREAD

**Issue by achachej** [brbeaird/SmartThings_MyQ#112]
Hello,

FIRST i would like to congratulate brbeaird for creating this. I ended in a catch 21 situation with a new Liftmaster "smart opener" and my beloved GOCONTROL system not working anymore due to rolling codes. 

The app works very well. My only question is why it added a door sensor icon for the actual garage opener and not a garage door ? 

I did setup the system using a ST sensor on the garage door to detect the open closed status. Maybe it is why.

Any idea why this happened or how to change to a garage icon ?

Thanks !

**Comment by brbeaird** [comment]
The way the new app deals with icons is weird. I'll see if I can get that fixed again.

**Comment by brbeaird** [comment]
This is FINALLY fixed in the latest version I pushed. HOWEVER, because of the weirdness of how custom device types work, you will likely not see the change take effect until you either delete the door device and re-add it or else go into the IDE and rename the door; even then, it may take up to an hour before you see the new icon in the app. It's a pain, but it will work eventually, and it's pretty nice seeing a garage door icon again.
