### ISSUE TITLE
New install does not work

### ISSUE THREAD

**Issue by scottha4** [brbeaird/SmartThings_MyQ#113]
Using latest build and MyQ Hub, insalled with no issues (no sensor), linked to myQ and device.  
MyQ Lite app tile shows cloud icons
![IMG_1945](https://user-images.githubusercontent.com/24880668/103248461-af1f6a80-4938-11eb-9805-ebda149de609.jpeg)
 and when I try the switches, I get spinning for 30 sec, then "a network error occurred.  Try again later."
IDE debug shows no errors for app and device upon install, and no debug updates at all when trying to refresh the app tile or clicking on the buttons.  
I tried removing and re-installing with and without switches.  Also tried to add a multi-sensor.  No luck with switches, but now garage door will trigger open and close based on the state of the sensor.  Works great with MyQ app itself.
Next steps, please?
thanks!

**Comment by brbeaird** [comment]
I'm sorry to say the no-sensor version of the app is pretty screwed right now. I still hope to get it working again once the fix some of the custom device handler stuff. If you do decide to go with a sensor on the door, that version is still working well.

**Comment by mikex99** [comment]
I just installed the no-sensor version and ran across the same issue.  I was able to get mine working by updating each of the 6 virtual devices created by the install.  Here are the steps to reproduce what I did.
1. Log into api.smartthings.com
2. Select your location (If you don't see your devices after you select your location, you may have installed the app at the root of your account instead of under your location.  You can logout, clear your browser cache, log back in to see the smart app and either move it to your locaion or delete it and then recreate it under your location.)
3. click My Devices
4. For each of the 6 devices, do the following
  1.  Click the device in the left collumn
  2.  Click Edit
  3. Click Update
  4. When you Update the virtual switches, it may trigger the action at that point.

My Door Control and Garage Door Control now display as unknown instead of the cloud error.
