### ISSUE TITLE
Not Opening on arrival

### ISSUE THREAD

**Issue by jmac1604** [brbeaird/SmartThings_MyQ#25]
Hello,

Thanks so much for the Code as I got it up and running in smart things. I can manually open and close my door, but I have it to open the garage door as I arrive home (using my phone as a sensor), but, the door is not opening?

Is there something I may be doing wrong? Or, do I need the actual sensor?

Thanks,

**Comment by brbeaird** [comment]
If you don't have a SmartThings-compatible sensor on the door, you won't be able to open/close the door via normal routines because SmartThings won't always send the open or close command if it does not know if the door is already opened or closed. However, it is possible to set up a rule in something like CoRE if you select the option to disable status optimization. This tells CoRE to always send the desired command regardless of whether SmartThings thinks the door is already opened/closed.

That said, the best alternative I'd suggest would be to add a sensor to the door.

**Comment by jmac1604** [comment]
Thanks, Brian for the quick reply! I will buy a sensor and get that up and running and connected to smart things and have it connected to my door. 

Another quick question.  I used your Tp link code.  Your the man! But, Can I set these on a schedule like I could through the kasa app? 

To have them come in In morning and off when I leave? Or even when I’m on vacation? Thanks

**Comment by brbeaird** [comment]
TP Link? Not quite sure I follow on that. You sure that was me?
