### ISSUE TITLE
Automations/Routines

### ISSUE THREAD

**Issue by azagent** [brbeaird/SmartThings_MyQ#39]
I have 2 questions:

Question 1:
I followed the directions and was able to get everything set up in the smartthings app.  When I push the button on the app the garage doors open and close.  However, I have set up a routine to open and close the door based on my location (coming or going) and neither will operate the door.  Do I need a smartthings hub to make the routine operate? I assumed since this runs in the cloud and not local that I would not need a hub.  

Question 2:
I also, have a Google home which does not recognize any commands to open or close the doors.  How can I set up my Google home?

Please help.
Thanks!

**Comment by brbeaird** [comment]
1.) Routines will not work correctly with this unless you have a physical sensor (and with that, a hub) that can tell whether the door is currently open or closed. This is because SmartThings assumes the door is already open or closed and won't actually send commands correctly each time.

2.) I believe it's similar to Alexa where you to say "turn on <push button switch name>" and "turn off <push button switch name>". I honestly have no idea how well that works without a hub, though.
