### ISSUE TITLE
Use api to get door status

### ISSUE THREAD

**Issue by tony-gutierrez** [brbeaird/SmartThings_MyQ#41]
I found it rather trivial to modify the code to get the door status from the api. Why is this not the default??

**Comment by zzatihz1** [comment]
I currently have SmartThings and MyQ integration is something that I have been looking for. Frankly, I find SmartThings limiting but relatively simple to use. I also recently started exploring Home Assistant and OpenHAB. Both have significantly more capabilities but also more complicated to use. OpenHAB does have an effective MyQ integration including the ability to read door status via the API. The default polling interval is 1 minute. As far as I can tell from reading the forums, this has not posed any significant problems for the MyQ service. Of course, anything can change.

With that said, I am interested in knowing @brbeaird or @tony-gutierrez would mind sharing the code including the door status. I am interested in trying it at my own risk.

Thanks in advance.

**Comment by brbeaird** [comment]
You can find the code in the original repo this was forked from here:  https://github.com/copy-ninja/SmartThings_MyQ - just look for the refresh method to see it calling the door status endpoint each time.

I can't really speak to other platforms that are able to poll. Maybe their user base hasn't been large enough for MyQ to care. Or maybe it's because the design of those systems do not result in MyQ getting hammered from a single set of (SmartThings cloud) IP's. All we know for sure is that MyQ and ST shut this down once, and if too many people start polling again every minute, they will find a way to do it again.

**Comment by zzatihz1** [comment]
Got it. One of my objections to ST is its dependence on the cloud. That's one reason I am exploring OpenHAB. ST fails miserably when you lose internet connectivity as we recently did for 26+ hours. OpenHAB (and other solutions) run locally and can be exposed to the cloud but not be dependent on it for daily operation.

Thank you for the quick response. I'm not sure what direction I will go with yet and certainly appreciate what your contributions to the ST community.

**Comment by brbeaird** [comment]
I definitely hear you there - I use locally-enabled rules for SmartThings wherever possible, and the majority of my lighting rules do work well for the most part even if my house loses connectivity.

Of course, MyQ itself is cloud-based, so if you lose connectivity, your door's remote control ability is dead no matter what platform you're using. I would be so stoked if there was a way to execute commands to the MyQ gateway via LAN.
