### ISSUE TITLE
Is it working now with new app?

### ISSUE THREAD

**Issue by Obelix25860** [brbeaird/SmartThings_MyQ#47]
I used this app with a couple of years and it is great (thanks a ton brbeaird!!).  Then I updated to the new app, and bam, all gone.  I saw an issue stream about getting it to work with the new app, and went and updated my Device Handlers ... does this now work with the new app?  If yes, how do I get to it?  In automations like before?

Thanks!

**Comment by brbeaird** [comment]
If you're using custom apps like this one, I would recommend you not use the new app yet and stick with the classic app. That said, if you get this installed with the latest device handler code, I believe it does 
at least partially work with the new app, although honestly I've not played with it much because I still mainly use the classic app. One thing I'm not sure on is if you can even install this app in the new app - you may need to open the classic app, go through the install steps, then have the doors be available in the new app.

**Comment by Obelix25860** [comment]
Would love to switch to the old app, but it won't let me login since it moved my account... And given the number of devices I really don't want to set it all up from scratch - do you know of another way to move back to the classic app? 

On the new app, I updated the custom app and handlers and now I'm able to open the doors from the ST app, but not close them. I'll test it again tonight with dedicated open/close buttons and will let you know. 



⁣Sent from my phone — funny grammar courtesy of autocorrect ​

**Comment by brbeaird** [comment]
Switching to a Samsung account does not force you to use the new app. There is definitely a way to log into the classic app after that. Check with ST support if you're still having trouble.
